# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0031_auto_20170630_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100, verbose_name='昵称')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('home_url', models.URLField(blank=True, verbose_name='个人主页')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改日期')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否显示')),
                ('star', models.PositiveIntegerField(verbose_name='赞')),
                ('un_star', models.PositiveIntegerField(verbose_name='踩')),
                ('pid', models.ManyToManyField(related_name='_comment_pid_+', to='comments.Comment', verbose_name='父节点')),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_time'],
            },
        ),
    ]
