# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.PositiveIntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='un_star',
            field=models.PositiveIntegerField(default=0, verbose_name='踩'),
        ),
    ]
