# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='测试数据')),
            ],
            options={
                'verbose_name': '测试评论',
                'verbose_name_plural': '测试评论',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
