# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户IP'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_source',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='来源'),
        ),
    ]
