# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170608_1048'),
        ('comments', '0003_auto_20170613_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='文章'),
            preserve_default=False,
        ),
    ]
