# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20170929_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='来源'),
        ),
    ]
