# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:35
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否公开')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '关于我',
                'verbose_name': '关于我',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='分类')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '分类',
                'ordering': ['-created_time'],
                'verbose_name': '分类',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联系人')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=255, verbose_name='主题')),
                ('message', models.TextField(verbose_name='内容')),
                ('is_pub', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '游客留言',
                'ordering': ['-created_time'],
                'verbose_name': '游客留言',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('excerpt', models.TextField(blank=True, max_length=200, verbose_name='摘要')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ['-create_time'],
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '标签',
                'ordering': ['-created_time'],
                'verbose_name': '标签',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
