# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
