# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 02:05
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170607_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default=''),
        ),
    ]
