# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170608_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('is_pub', models.BooleanField(default=True, verbose_name='是否公开')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='访问量')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
