# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170614_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_pub',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_pub',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_time',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='about',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_time',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified_time',
            field=models.DateTimeField(verbose_name='修改日期'),
        ),
    ]
