# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170614_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_original',
            field=models.BooleanField(default=True, verbose_name='是否原创'),
        ),
    ]
