# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_is_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='站点名称')),
                ('site_url', models.CharField(max_length=150, verbose_name='站点地址')),
                ('admin_name', models.CharField(max_length=30, verbose_name='站长名称')),
                ('admin_contact', models.CharField(max_length=200, verbose_name='站长联系方式')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('is_pub', models.BooleanField(default=False, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '链接互换',
                'verbose_name_plural': '链接互换',
            },
        ),
    ]
