# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_friendsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsite',
            name='site_url',
            field=models.URLField(max_length=150, verbose_name='站点地址'),
        ),
    ]
