# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170615_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='created_time',
            field=models.DateTimeField(auto_created=True, verbose_name='请求时间'),
        ),
    ]
