# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170615_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='http_user_agent',
            field=models.CharField(max_length=350, verbose_name='agent'),
        ),
    ]
