# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170616_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrecord',
            name='http_referer',
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='http_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='path'),
            preserve_default=False,
        ),
    ]
