# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170616_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visit', models.PositiveIntegerField(default=0, verbose_name='总共访问量')),
                ('today_visit', models.PositiveIntegerField(default=0, verbose_name='今日访问量')),
                ('total_ip', models.PositiveIntegerField(default=0, verbose_name='总共访问IP')),
                ('today_ip', models.PositiveIntegerField(default=0, verbose_name='今日访问IP')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '运营统计',
                'verbose_name_plural': '运营统计',
            },
        ),
    ]
