# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_visitstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitstatistics',
            name='created_date',
            field=models.DateField(unique=True, verbose_name='日期'),
        ),
    ]
