# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170617_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
                ('is_disable', models.BooleanField(default=True, verbose_name='是否禁止')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('deny_reason', models.CharField(choices=[('1', '爬虫'), ('2', '破解密码'), ('3', '不友好用户')], default='1', max_length=20)),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
            },
        ),
    ]
