# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170617_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_time',
            field=models.DateTimeField(null=True, verbose_name='修改日期'),
        ),
    ]
