# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170618_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='http_path',
            field=models.CharField(max_length=500, verbose_name='path'),
        ),
    ]
