# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_contact_is_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=400, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=100, verbose_name='主题'),
        ),
    ]
