# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20170630_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
