# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20170630_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
